# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('0', 'Completed'), ('1', 'In Progress'), ('2', 'On Hold'), ('5', 'Abandoned')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contibutions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
