# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20190624_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='progress',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('0', 'Completed'), ('1', 'In Progress'), ('2', 'On Hold'), ('5', 'Abandoned')], default='1', max_length=1),
        ),
    ]
