# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-25 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20190625_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='upvotes',
            new_name='upvoted_by',
        ),
    ]
