# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20190625_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('0', 'Completed'), ('1', 'In Progress'), ('2', 'Submitted'), ('3', 'On Hold'), ('5', 'Abandoned')], default='2', max_length=1),
        ),
    ]
