# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20190626_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
