# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_ticket_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('0', 'Highest-paid'), ('1', 'Completed'), ('2', 'In Progress'), ('3', 'Submitted'), ('4', 'On Hold'), ('5', 'Abandoned')], default='3', max_length=1),
        ),
    ]
